# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Serhan Baker
tagline:          'Homepage'
description:      'Thoughts and codes'
#url:              http://localhost:4000
url:              http://serhanbaker.io
baseurl:          /

author:
  name:           'Serhan Baker'
  url:            https://twitter.com/serhanbaker

paginate:         5

# Custom vars
github: serhanbaker
twitter: serhanbaker
instagram: serhan_baker
linkedin: serhanbaker
projectpage: projects
